services:
  cache:
    image: valkey/valkey:latest
    command: ["valkey-server", "--appendonly", "yes"]
    ports: ["6379:6379"]
    #volumes: [valkey-data:/data]
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 3s
      timeout: 2s
      retries: 10

  api:
    develop:
      watch:
        - path: ./api/
          target: /usr/src/app
          action: sync
        - path: ./api/package.json
          action: rebuild
        - path: ./api/package-lock.json
          action: rebuild
    build:
      context: ./api
      target: dev
    command: npm run dev
    environment:
      NODE_ENV: development
      VALKEY_HOST: cache
      VALKEY_PORT: "6379"
      API_KEY: "test-api-key"
      VALHEIM_SERVER_NAME: "Test Server"
      SERVER_MAX_PLAYERS: "10"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"
    ports: ["3000:3000"]
    # volumes:
    # - ./api:/usr/src/app
    # keep container's node_modules separate so the bind doesn't overwrite them
    # - /usr/src/app/node_modules
    depends_on:
      cache:
        condition: service_healthy
  valheim:
    image: lloesche/valheim-server:latest
    cap_add: ["SYS_NICE"]
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    env_file: .env.valheim
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # API Regex - send all log lines to api server
      VALHEIM_LOG_FILTER_REGEXP_All: ".*"
      ON_VALHEIM_LOG_FILTER_REGEXP_All: >-
        { read l; msg="$$l"; curl -sfSL -m 2 -X POST -H "Content-Type: application/json" -H "x-api-key: $${API_KEY}" -d "{\"line\":\"$${msg//\"/\\\"}\"}" "$${API_URL:-http://api:3000}/ingest/log"; }

volumes:
  valkey-data:
